// <auto-generated />
namespace WAD_T2104E_NguyenHoangSon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productDBMigration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productDBMigration2));
        
        string IMigrationMetadata.Id
        {
            get { return "202209131548557_productDBMigration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
